package ramzi.eljabali.justjog.ui.design

import androidx.compose.material3.darkColorScheme
import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val black = Color(0xFF000000)
val white = Color(0xFFFFFFFF)
val primaryBackgroundColor = Color(0xFF474245)
val secondaryBackgroundColor = Color(0xFF121212)
val primaryTextColor = Color(0xFFFFFFFF)
val secondaryTextColor = Color(0xFF9B9B9B)
val primaryButtonColor = Color(0xFFBB86FC)
val lightBlue = Color(0xFF00C2FF)

val primaryDarkHighContrast = Color(0xFFF1FDFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF86D7E5)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF1FDFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB5CFD4)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFCFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBECAEF)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0E1415)
val onBackgroundDarkHighContrast = Color(0xFFDEE3E5)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F484A)
val onSurfaceVariantDarkHighContrast = Color(0xFFF3FCFE)
val outlineDarkHighContrast = Color(0xFFC3CCCE)
val outlineVariantDarkHighContrast = Color(0xFFC3CCCE)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF002F35)
val surfaceDimDarkHighContrast = Color(0xFF0E1415)
val surfaceBrightDarkHighContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF090F10)
val surfaceContainerLowDarkHighContrast = Color(0xFF171D1E)
val surfaceContainerDarkHighContrast = Color(0xFF1B2122)
val surfaceContainerHighDarkHighContrast = Color(0xFF252B2C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303637)

